# Generated by Django 5.1.4 on 2024-12-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directs", "0003_auto_20220213_2344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
