# Generated by Django 5.1.4 on 2024-12-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0007_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
